version: '2.1'

services:
  db: 
    image: mysql:latest
    container_name: msql
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=db1
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d  
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "db"]
      timeout: 20s
      retries: 10   
  webapp:
    build: 
      context: ./ 
      dockerfile : ./mtomcat-Dockerfile
    container_name: mtomcat
    ports:
      - "8080:8080" 
    links:
      - db  
    depends_on:
       db:
        condition: service_healthy  
      



   