version: '3'

services:
  db: 
    image: mysql:latest
    container_name: msql
    environment:
      - MYSQL_ROOT_PASSWORD=root 
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d  
  webapp:
    build: 
      context: ./ 
      dockerfile : ./mtomcat-Dockerfile
    container_name: mtomcat
    ports:
      - "8080:8080" 
    depends_on:
      - db  
   